services:
  conjecscore-app:
    build: .
    env_file:
      - app/.env
    volumes:
      - main-db:/var/data
    ports:
      - "8000:8000"
    container_name:
      app
  nginx-proxy:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../certs:/etc/cloudflare
    container_name:
      proxy
volumes:
  main-db:
