name: Docker CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  # For the CI.
  SECRET: "TEST_SECRET"
  POSTGRES_USER: test_user
  POSTGRES_PASSWORD: test_password
  POSTGRES_DB: test_db
  DATABASE_URL: "postgresql+asyncpg://test_user:password@localhost:5432/testdb"

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: test_db
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v6

    - name: Install backend dependencies
      uses: astral-sh/setup-uv@v6

    - name: Compile typescript.
      run: npx rust-just@latest ci
