name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install npm dependencies
      run: npm install

    - name: Install uv
      uses: astral-sh/setup-uv@v6

    - name: Run tests
      run: make ci
